export { default as BtnLink } from '@/views/Home/components/utils/BtnLink'
export { default as DialogEdit } from '@/views/Home/components/dialogs/DialogEdit'
export { default as InfoAdmin } from '@/views/Home/components/utils/InfoAdmin'
export { default as AlertNotifications } from '@/views/Home/components/notifications/AlertNotifications'
export { default as translateItem } from '@/utils/translateItem'
