export { default as BtnLink } from '@/views/Home/components/utils/BtnLink'
export { default as InfoAdmin } from '@/views/Home/components/dialogs/InfoAdmin'
export { default as DialogEdit } from '@/views/Home/components/dialogs/DialogEdit'
export { default as DialogDeleteUser } from '@/views/Home/components/dialogs/DialogDeleteUser'
export { default as DialogInsertUser } from '@/views/Home/components/dialogs/DialogInsertUser'
export { default as AlertNotifications } from '@/views/Home/components/notifications/AlertNotifications'
