export { default as BtnLink } from '@/views/Home/components/utils/BtnLink'
export { default as generateImgBase64 } from '@/utils/generateImgBase64'
export { default as InfoAdmin } from '@/views/Home/components/utils/InfoAdmin'
export { default as showPhotoUser } from '@/views/Home/components/dialogs/showPhotoUser'
export { default as DialogEdit } from '@/views/Home/components/dialogs/DialogEdit'
export { default as DialogDeleteUser } from '@/views/Home/components/dialogs/DialogDeleteUser'
export { default as DialogInsertUser } from '@/views/Home/components/dialogs/DialogInsertUser'
export { default as AlertNotifications } from '@/views/Home/components/notifications/AlertNotifications'
